version: "3"
services:
  sitespeed:
    image: ${DOCKER_REGISTRY}sitespeedio/sitespeed.io
    command: "/usr/src/app/bin/sitespeed.js --config /performance/config/config-chrome.json --preScript /performance/scripts/preScript.js http://demo:8080"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=${no_proxy}
    networks: 
      - local
    shm_size: 2g
    volumes:
      - ./performance/config:/performance/config/
      - ./performance/scripts:/performance/scripts/
  demo:
    image: ${DOCKER_REGISTRY}milieuinfo/node:12
    container_name: demo
    hostname: demo
    working_dir: /home/node/app
    entrypoint: bash -c "npm install && npm run demo"
    networks: 
      - local
    ports:
      - 8080:8080
    volumes:
      - .:/home/node/app

networks:
  local:
    driver: bridge
