version: "3"
services:
  sitespeed:
    image: ${DOCKER_REGISTRY}sitespeedio/sitespeed.io
    command: "--config /performance/config/config-chrome.json http://demo:8080/performance/performance.html"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=${no_proxy}
    shm_size: 2g
    volumes:
      - ./performance/config:/performance/config/
      - ./performance/scripts:/performance/scripts/
  demo:
    image: ${DOCKER_REGISTRY}node:12
    container_name: demo
    hostname: demo
    working_dir: /home/node/app
    entrypoint: bash -c "npm run demo"
    volumes:
      - .:/home/node/app
