version: "3"
services:
  sitespeed-chrome:
    image: ${DOCKER_REGISTRY}sitespeedio/sitespeed.io
    command: "--config /performance/config/config-chrome.json --preScript /performance/scripts/preScript.js http://demo:8080/performance/performance.html"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=${no_proxy}
    shm_size: 2g
    volumes:
      - ./performance/config:/performance/config/
      - ./performance/scripts:/performance/scripts/  
      - ./performance/results/chrome/:/sitespeed.io/chrome-results/
  sitespeed-firefox:
    image: ${DOCKER_REGISTRY}sitespeedio/sitespeed.io
    command: "--config /performance/config/config-firefox.json --preScript /performance/scripts/preScript.js http://demo:8080/performance/performance.html"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=${no_proxy}
    shm_size: 2g
    volumes:
      - ./performance/config:/performance/config/
      - ./performance/scripts:/performance/scripts/
      - ./performance/results/firefox/:/sitespeed.io/firefox-results/
  demo:
    image: ${DOCKER_REGISTRY}milieuinfo/node:12
    container_name: demo
    hostname: demo
    working_dir: /home/node/app
    entrypoint: bash -c "npm install && npm run demo"
    volumes:
      - .:/home/node/app
